### ISSUE TITLE
Offline import/export

### ISSUE THREAD

**Issue by Paol-M** [1RandomDev/showly-oss#3]
The ability to import and export app data without having to sign in to Trakt would be amazing. Thank you 😊

**Comment by 1RandomDev** [comment]
I currently don't plan on adding completely new features to the app. My goal is just making the [Showly App](https://github.com/michaldrabik/showly-2.0) available in a privacy friendly way and without trackers. So I would suggest you request this feature for the official app and as soon as it gets implemented I will merge it into my fork.

**Comment by Paol-M** [comment]
Oh, okay. Thank you.

**Comment by ngocanhtve** [comment]
I use a backup and restore software, which of course requires root access.

But I also think an official backup feature built-in is great. It helps non-root users still use it well. And what's more, offline backup is one of the most valuable features of an OSS.
