### ISSUE TITLE
Showly OSS is not showing IMDb/Rotten Tomatoes score

### ISSUE THREAD

**Issue by itsluminous** [1RandomDev/showly-oss#4]
The playstore app works fine, but fdroid version does not work
My version : 3.21.0

**Comment by 1RandomDev** [comment]
For me the 2 scores show up in the details page exactly like in the playstore app. With which movies exactly do you have this problem, because it seems like not all movies have both scores?

**Comment by itsluminous** [comment]
yes, you are right
some movies it is working and some it is not.
Eg "Don't Look Up" is a 2021 movie which definitely has a rating on IMDB and Rotten Tomatoes
and it is not showing in both OSS and Play Store version

**Comment by 1RandomDev** [comment]
Okay when it also happens in the PlayStore version it's probably something that upstream dev has to fix in [michaldrabik/showly-2.0](https://github.com/michaldrabik/showly-2.0). But unfortunately it looks like it can't be fixed without switching to a completely new API. The scores are provided by the [OMDB API](https://www.omdbapi.com/) and for the movie "Don't Look Up" it only shows a IMDb and Metacritic score.

**Comment by itsluminous** [comment]
ok then should i close this bug?

**Comment by itsluminous** [comment]
Raised a bug in showly 2.0
https://github.com/michaldrabik/showly-2.0/issues/694
