### ISSUE TITLE
Add new language to Crowdin

### ISSUE THREAD

**Issue by ngocanhtve** [1RandomDev/showly-oss#8]
Please add Vietnamese, I just joined the project on crowdin but don't have Vietnamese yet to be able to translate.

**Comment by 1RandomDev** [comment]
I'm just maintaining this OSS fork of the Showly app and I don't have any access to the Crowdin project, for that you would need to ask the original author at https://github.com/michaldrabik/showly-2.0

**Comment by ngocanhtve** [comment]
Thank for your answer!

**Comment by ngocanhtve** [comment]
@1RandomDev Can I make a pull request to the repository for this OSS version? Cause the original is currently not accepting additional new languages.

**Comment by 1RandomDev** [comment]
Since a language will not require much maintenance in the future, I would be happy to merge it. I currently just don't have the time to do more than updating the app for every upstream release and therefor will not merge any large requests that add/modify features and can break on every update.

**Comment by ngocanhtve** [comment]
I will complete the translation for the pull request soon. Thank.

**Comment by ngocanhtve** [comment]
@1RandomDev I have completed the translation and have created a pull request. Hope you take some time to take a look. Thank you!

**Comment by 1RandomDev** [comment]
Merged, thanks for your contribution! The changes will be released together with the next upstream update.
